#include <string>

#include "version.h"

// Name of client reported in the 'version' message. Report the same name
// for both bitcoind and bitcoin-qt, to make it harder for attackers to
// target servers or GUI users specifically.
const std::string CLIENT_NAME("DigitalNoteoshi");

// Client version number
#define CLIENT_VERSION_SUFFIX   "DigitalNote-Core"


// The following part of the code determines the CLIENT_BUILD variable.
// Several mechanisms are used for this:
// * first, if HAVE_BUILD_INFO is defined, include build.h, a file that is
//   generated by the build environment, possibly containing the output
//   of git-describe in a macro called BUILD_DESC
// * secondly, if this is an exported version of the code, GIT_ARCHIVE will
//   be defined (automatically using the export-subst git attribute), and
//   GIT_COMMIT will contain the commit id.
// * then, three options exist for determining CLIENT_BUILD:
//   * if BUILD_DESC is defined, use that literally (output of git-describe)
//   * if not, but GIT_COMMIT is defined, use v[maj].[min].[rev].[build]-g[commit]
//   * otherwise, use v[maj].[min].[rev].[build]-unk
// finally CLIENT_VERSION_SUFFIX is added

// v2.0.0.8: the build.h / HAVE_BUILD_INFO path is deliberately disabled.
//
// build.h was generated by share/genbuild.{bat,sh} and defined BUILD_DESC
// from `git describe`.  That made the reported version depend on the
// repository's git tag state -- which is only knowable AFTER a build, and
// on this repo produced a misleading string (the most recent reachable
// tag was an old v1.0.x, so `git describe` reported v1.0.x-<n>-g<hash>
// for a v2.0.0.8 codebase).
//
// The version is now controlled entirely by clientversion.h: with
// BUILD_DESC left undefined here, the #ifndef BUILD_DESC fallback below
// builds it from CLIENT_VERSION_MAJOR/MINOR/REVISION/BUILD, giving a
// clean, file-controlled "v2.0.0.8-XDN-DigitalNote-Core".
//
// The build also no longer passes USE_BUILD_INFO=1 to qmake, so
// HAVE_BUILD_INFO is not defined and this block would not activate even
// if uncommented.  To reinstate git-derived build info later: restore
// USE_BUILD_INFO=1 in the build, uncomment this block, AND ensure the
// repository carries a correct v2.0.0.x tag reachable from HEAD.
//
// // First, include build.h if requested
// #ifdef HAVE_BUILD_INFO
// #include "../build/build.h"
// #endif // HAVE_BUILD_INFO

// git will put "#define GIT_ARCHIVE 1" on the next line inside archives. 
#define GIT_ARCHIVE 1

#ifdef GIT_ARCHIVE
#define GIT_COMMIT_ID "XDN-"
#endif // GIT_ARCHIVE

#define BUILD_DESC_FROM_COMMIT(maj,min,rev,build,commit) \
	"v" DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build) "-" commit

#define BUILD_DESC_FROM_UNKNOWN(maj,min,rev,build) \
	"v" DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build) "-"

#ifndef BUILD_DESC
	#ifdef GIT_COMMIT_ID
		#define BUILD_DESC BUILD_DESC_FROM_COMMIT(CLIENT_VERSION_MAJOR, CLIENT_VERSION_MINOR, CLIENT_VERSION_REVISION, CLIENT_VERSION_BUILD, GIT_COMMIT_ID)
	#else // GIT_COMMIT_ID
		#define BUILD_DESC BUILD_DESC_FROM_UNKNOWN(CLIENT_VERSION_MAJOR, CLIENT_VERSION_MINOR, CLIENT_VERSION_REVISION, CLIENT_VERSION_BUILD)
	#endif // GIT_COMMIT_ID
#endif // BUILD_DESC

#ifndef BUILD_DATE
	#ifdef GIT_COMMIT_DATE
		#define BUILD_DATE GIT_COMMIT_DATE
	#else // GIT_COMMIT_DATE
		#define BUILD_DATE __DATE__ ", " __TIME__
	#endif // GIT_COMMIT_DATE
#endif // BUILD_DATE

const std::string CLIENT_BUILD(BUILD_DESC CLIENT_VERSION_SUFFIX);
const std::string CLIENT_DATE(BUILD_DATE);
